version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
      - 3001:3001 # React Email
      - 4983:4983 # Drizzle studio
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_URL=${DB_URL:-postgres://postgres:postgres@db:5432/postgres}
      - MAIL_HOST=${MAIL_HOST:?error}
      - MAIL_PORT=${MAIL_PORT:?error}
      - MAIL_SECURE=${MAIL_SECURE:?error}
      - MAIL_USER=${MAIL_USER:?error}
      - MAIL_PASSWORD=${MAIL_PASSWORD:?error}

  db:
    image: postgres:16.2-alpine3.19
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-postgres}

volumes:
  db-data:
